import { Alert } from 'react-native';
import { apiRequest } from './apiRequest-services';

const mockTfcConteinerInspecaoLacreResumoBuscar = {
  "aCoEntity": null,
  "alsUpdate": [],
  "TFCCONTEINERINSPECAOAVARIARESUMODTO": {
      "aCoEntity": null,
      "alsUpdate": [],
      "TFCCONTEINERINSPECAOAVARIAID": 0.0,
      "TFCCONTEINERINSPECAOID": 0.0,
      "TFCCONTEINERINSPECAODTO": {
          "aCoEntity": null,
          "alsUpdate": [],
          "TFCCONTEINERINSPECAOID": 0.0,
          "TFCCONTEINERINSPECAORIID": null,
          "TFCCONTEINEROPERACAOID": null,
          "TFCCONTEINERGMPREVISAOID": null,
          "EXTERNALID": null,
          "NROCONTEINER": "",
          "CODIGOISO": null,
          "CEALTURA": null,
          "CEDIREITA": null,
          "CEESQUERDA": null,
          "CEFRONTAL": null,
          "CESETTING": null,
          "CETRASEIRO": null,
          "CEVENTILACAO": null,
          "GENSET": "",
          "OCORRENCIA": "0001-01-01T00:00:00",
          "OCORRENCIA_STRING": null,
          "SAFEWEIGHT": null,
          "TARA": null,
          "TIPO": 0,
          "TIPO_DESCRIPTION": null,
          "LONGARINA": null,
          "SEMLACRE": null,
          "TRA": "",
          "FREIGHTKIND": "",
          "MODALIDADE": "",
          "SIGLAMODALIDADE": "",
          "SIGLAFREIGHTKIND": "",
          "FINALIZADO": null,
          "FINALIZADO_STRING": null,
          "SIGLATIPODOCUMENTO": null,
          "TEMPO_TRANSACAO": null,
          "USUARIO": "",
          "DAMAGEREPORT": null,
          "CPFMOTORISTA": null,
          "REMOTORISTA": null,
          "LANE": null,
          "ITVTRANSFERENCIA": null,
          "ITV": null,
          "TIPOENUM": 0,
          "LONGARINAENUM": null,
          "PLACADANIFICADA": false,
          "TFCVEICULOID": 0.0,
          "ISIMO": 0.0,
          "ISTRANSFERENCIA": 0,
          "NextAction": "",
          "PrevAction": "",
          "ActionReferenceId": 0.0,
          "_IOP": false,
          "UID": 0.0,
          "aCoMessageList": []
      },
      "AVARIAS": "",
      "isOPENTOP": false,
      "COMPONENTS": [
          {
              "GKEY": 113776.0,
              "ID": "A",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Assoalho",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.58",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113776.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113780.0,
              "ID": "D",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lateral Direita",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.985",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113780.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113777.0,
              "ID": "E",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lateral Esquerda",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.829",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113777.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113779.0,
              "ID": "F",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Painel Frontal",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.97",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113779.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113785.0,
              "ID": "G",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Geral",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.767",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113785.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113786.0,
              "ID": "K",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Flat Rack",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.907",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113786.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 4515345804.0,
              "ID": "M",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Genset Geral",
              "EQ_CLASS": "ACCESSORY",
              "CREATED": "2023-12-12T11:34:02.619",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 0.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113778.0,
              "ID": "P",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Porta",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.954",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113778.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113801.0,
              "ID": "R",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Reefer",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:07.016",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113801.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 113787.0,
              "ID": "T",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Teto",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-03-20T10:56:06.938",
              "LIFE_CYCLE_STATE": "ACT",
              "UID": 113787.0,
              "aCoMessageList": []
          }
      ],
      "TYPES": [
          {
              "GKEY": 187214.0,
              "ID": "10",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Amassado / arranhado / enferrujado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.136",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 0,
              "CUSTDFF_ORDEM": null,
              "UID": 187214.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187186.0,
              "ID": "00",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Afundado / estufado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.827",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 0,
              "CUSTDFF_ORDEM": null,
              "UID": 187186.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187203.0,
              "ID": "01",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Furado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.512",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187203.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187193.0,
              "ID": "26",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Porta semi aberta ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:36.904",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187193.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187199.0,
              "ID": "25",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Vedacao avariada ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.262",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187199.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187197.0,
              "ID": "02",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Remendo / solda / pintura",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.122",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 0,
              "CUSTDFF_ORDEM": null,
              "UID": 187197.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187206.0,
              "ID": "27",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Trinco/haste/guia/parafuso avariado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.684",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187206.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187179.0,
              "ID": "03",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina superior avariada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.094",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187179.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187213.0,
              "ID": "04",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina inferior avariada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.089",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187213.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 648618724.0,
              "ID": "100",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina Inferior Cortada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-28T09:14:09.339",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 648618724.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187204.0,
              "ID": "12",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lacre violado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.59",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187204.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187176.0,
              "ID": "13",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lacre ilegivel",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:34.954",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187176.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187180.0,
              "ID": "16",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Rotulos antigos ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.484",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187180.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187198.0,
              "ID": "15",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Ausencia de rotulos",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.184",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187198.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187181.0,
              "ID": "23",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Carga exposta ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.531",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187181.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 648618539.0,
              "ID": "98",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina Superior Cortada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-28T09:13:08.232",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 648618539.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 648618640.0,
              "ID": "99",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina Superior Furada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-28T09:13:42.335",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 648618640.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 340175.0,
              "ID": "47",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lona sem Lacre",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-06-22T09:48:50.811",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 340175.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561893.0,
              "ID": "72",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Plug 440V (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:18:25.495",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222561893.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 648618736.0,
              "ID": "101",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina Inferior Furada.",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-28T09:14:34.487",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 648618736.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561943.0,
              "ID": "73",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Plug 440V (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:18:54.965",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222561943.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561659.0,
              "ID": "70",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Cabo 440V (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:17:22.875",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222561659.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561878.0,
              "ID": "71",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Cabo 440V (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:17:54.279",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222561878.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382780.0,
              "ID": "50",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Guard rail/compartimento (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:29:26.478",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 105382780.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222560253.0,
              "ID": "62",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Guard rail/compartimento (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:09:43.35",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222560253.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 318684706.0,
              "ID": "83",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Janela de Ventilacao Avariada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2015-06-09T10:35:25.642",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 318684706.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187215.0,
              "ID": "17",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Vazando ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.199",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187215.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 627219135.0,
              "ID": "96",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Cortado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-13T15:24:29.075",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 627219135.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 627220446.0,
              "ID": "97",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Rasgado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-13T15:24:44.8",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 627220446.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187201.0,
              "ID": "06",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina superior remendada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.372",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187201.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187173.0,
              "ID": "07",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Longarina inferior remendada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:34.735",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187173.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187209.0,
              "ID": "08",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Corner post remendado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.855",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187209.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187190.0,
              "ID": "09",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Helice ventilador (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:36.404",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187190.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 676471747.0,
              "ID": "102",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Travessa avariada / faltante",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-05-12T15:10:36.082",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 676471747.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 1883330098.0,
              "ID": "103",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "EMBALAGEM DIVERGENTE",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2017-05-29T15:57:04.478",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 1883330098.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 3317907383.0,
              "ID": "104",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "LACRE ARMADOR 4 HASTE",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2020-05-28T08:49:02.063",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 0.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 4043803553.0,
              "ID": "105",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Vedacao remendada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2022-07-11T15:39:52.676",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 0,
              "CUSTDFF_ORDEM": null,
              "UID": 0.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 4515345774.0,
              "ID": "106",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Estrutura/Paineis/Motor",
              "EQ_CLASS": "ACCESSORY",
              "CREATED": "2023-12-12T11:28:47.827",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 0,
              "CUSTDFF_ORDEM": null,
              "UID": 0.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187185.0,
              "ID": "14",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lacre divergente",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.78",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187185.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187212.0,
              "ID": "18",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Valvula avariada / faltante ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.027",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187212.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187174.0,
              "ID": "19",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Divergencia de peso ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:34.829",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187174.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187210.0,
              "ID": "20",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Suspeita comprometimento da carga",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.918",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187210.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187192.0,
              "ID": "21",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lona avariada / faltante",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:36.841",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187192.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187205.0,
              "ID": "22",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Embalagem avariada ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.637",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187205.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187216.0,
              "ID": "24",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Assoalho avariado / substituido ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.261",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187216.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187182.0,
              "ID": "28",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Trinco/haste/guia/paraf substituido",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.609",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187182.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187217.0,
              "ID": "29",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Sem travessas ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.308",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187217.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187194.0,
              "ID": "30",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Sem lona ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:36.982",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187194.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187177.0,
              "ID": "31",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lona solta ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187177.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187175.0,
              "ID": "32",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Sem cabo de aco",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:34.876",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187175.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187207.0,
              "ID": "33",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Cabo avariado ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.731",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187207.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187211.0,
              "ID": "34",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Cabo faltante ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.965",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187211.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187183.0,
              "ID": "35",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Cabo forca avariado ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.656",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187183.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187218.0,
              "ID": "36",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Plug faltando ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.355",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187218.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187189.0,
              "ID": "37",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Plug avariado ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.983",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187189.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187202.0,
              "ID": "38",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Motor avariado ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.45",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187202.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187187.0,
              "ID": "39",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Display faltando ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.89",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187187.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187195.0,
              "ID": "40",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Disco temp. faltando ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.028",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187195.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187208.0,
              "ID": "41",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Placa mae faltando ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.793",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187208.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187178.0,
              "ID": "42",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Controlador (Faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.047",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187178.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187200.0,
              "ID": "43",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Maquinario faltante ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.325",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187200.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187184.0,
              "ID": "44",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Peacao irregular ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.718",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187184.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187219.0,
              "ID": "45",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Trava / mola avariada ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:38.401",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187219.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187196.0,
              "ID": "46",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Partes moveis arreadas ",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:37.091",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 187196.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382644.0,
              "ID": "48",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Keypad/Keyboard (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:28:29.273",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 105382644.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382646.0,
              "ID": "49",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Paineis/grades/tampas (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:28:54.233",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 105382646.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382783.0,
              "ID": "51",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Plug 440V (pino guia - faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:29:54.09",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 105382783.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382795.0,
              "ID": "52",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Sensores/fiacao (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:30:16.991",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 105382795.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382891.0,
              "ID": "53",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Disco air vent (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:30:45.914",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 105382891.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382915.0,
              "ID": "54",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Parafusos/travas/nut (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:31:21.997",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 105382915.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382950.0,
              "ID": "55",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Tubos/conexoes/valvulas (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:31:46.083",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 105382950.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382966.0,
              "ID": "56",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Placas/reles/contatoras(avariadas)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:32:25.177",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 105382966.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382970.0,
              "ID": "57",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Keypad/keyboard (quebrado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:34:25.735",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 105382970.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382932.0,
              "ID": "58",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Paines/grades/tampas (avariados)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:34:53.519",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 105382932.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 105382972.0,
              "ID": "59",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Parafusos/travas/nut (avariados)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-01-20T08:35:27.277",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 105382972.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222560089.0,
              "ID": "60",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Disco air vent (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:08:09.124",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222560089.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222560052.0,
              "ID": "61",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Display avariado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:08:51.526",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222560052.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222560254.0,
              "ID": "63",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Motor faltando",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:10:02.258",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222560254.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222560337.0,
              "ID": "64",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Placas/reles/contatoras (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:10:58.918",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222560337.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222560427.0,
              "ID": "65",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Porta Controlbox (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:11:57.685",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222560427.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561211.0,
              "ID": "66",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Porta controlbox (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:14:32.987",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222561211.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561623.0,
              "ID": "67",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Controle atmosferico (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:15:18.868",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222561623.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561612.0,
              "ID": "68",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Partlow (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:15:58.15",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222561612.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561629.0,
              "ID": "69",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Tubos/conexoes/valvulas (quebrado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:16:41.956",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222561629.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222561913.0,
              "ID": "74",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Helice ventilador (quebrado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:19:31.017",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222561913.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222562251.0,
              "ID": "75",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "FC (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:20:01.11",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222562251.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222562601.0,
              "ID": "76",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Compressor (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:20:25.946",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 222562601.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222562632.0,
              "ID": "77",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "FC (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:20:51",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222562632.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222562760.0,
              "ID": "78",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Sensores/fiacao (solto)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:22:20.765",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222562760.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222562785.0,
              "ID": "79",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Solenoid (avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:23:09.563",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222562785.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 187188.0,
              "ID": "8",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Corner post avariado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2013-05-29T23:17:35.936",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 187188.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 222562810.0,
              "ID": "80",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Solenoid (faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-10-13T09:23:31.076",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 222562810.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 235662422.0,
              "ID": "81",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "FRAME (AVARIADO)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2014-11-14T16:50:25.288",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 235662422.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 277903661.0,
              "ID": "82",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Lacre Avariado",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2015-03-06T14:52:39.457",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 277903661.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 552560344.0,
              "ID": "84",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Escada Avariada",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-02-01T14:40:56.964",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 552560344.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607897637.0,
              "ID": "85",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "DISJUNTOR  (FALTANDO)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T13:55:03.321",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 607897637.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607897904.0,
              "ID": "86",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Sensores/Fiação (Avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T13:56:12.234",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607897904.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607898321.0,
              "ID": "87",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Controlador (Avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T13:57:33.173",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607898321.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607898563.0,
              "ID": "88",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Rmm (Faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T13:58:33.319",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607898563.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607899212.0,
              "ID": "89",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Rmm (Avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T13:59:36.005",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607899212.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607899492.0,
              "ID": "90",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "HPS (Avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T14:00:22.51",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607899492.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607899656.0,
              "ID": "91",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "HPS (Faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T14:01:07.054",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607899656.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607899939.0,
              "ID": "92",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Transformador 440/24V (Faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T14:02:53.169",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 607899939.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607899997.0,
              "ID": "93",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Transformador 440/24V (Avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T14:03:50.385",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 607899997.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 607900127.0,
              "ID": "94",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Partlow (Avariado)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-03-23T14:04:54.096",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": null,
              "CUSTDFF_ORDEM": null,
              "UID": 607900127.0,
              "aCoMessageList": []
          },
          {
              "GKEY": 624058960.0,
              "ID": "95",
              "REFERENCE_SET": 49.0,
              "DESCRIPTION": "Porta do Partlow (Faltando)",
              "EQ_CLASS": "CONTAINER",
              "CREATED": "2016-04-11T14:17:15.974",
              "LIFE_CYCLE_STATE": "ACT",
              "CUSTDFF_REPORTDAMAGE": 1,
              "CUSTDFF_ORDEM": null,
              "UID": 624058960.0,
              "aCoMessageList": []
          }
      ],
      "NextAction": "",
      "PrevAction": "",
      "ActionReferenceId": 0.0,
      "UID": 0.0,
      "aCoMessageList": []
  },
  "TFCCONTEINERINSPECAOLACRERESUMODTO": {
      "aCoEntity": null,
      "alsUpdate": [],
      "TFCCONTEINERINSPECAOID": 0.0,
      "TFCCONTEINERINSPECAODTO": {
          "aCoEntity": null,
          "alsUpdate": [],
          "TFCCONTEINERINSPECAOID": 0.0,
          "TFCCONTEINERINSPECAORIID": null,
          "TFCCONTEINEROPERACAOID": null,
          "TFCCONTEINERGMPREVISAOID": null,
          "EXTERNALID": null,
          "NROCONTEINER": "",
          "CODIGOISO": null,
          "CEALTURA": null,
          "CEDIREITA": null,
          "CEESQUERDA": null,
          "CEFRONTAL": null,
          "CESETTING": null,
          "CETRASEIRO": null,
          "CEVENTILACAO": null,
          "GENSET": "",
          "OCORRENCIA": "0001-01-01T00:00:00",
          "OCORRENCIA_STRING": null,
          "SAFEWEIGHT": null,
          "TARA": null,
          "TIPO": 0,
          "TIPO_DESCRIPTION": null,
          "LONGARINA": null,
          "SEMLACRE": null,
          "TRA": "",
          "FREIGHTKIND": "",
          "MODALIDADE": "",
          "SIGLAMODALIDADE": "",
          "SIGLAFREIGHTKIND": "",
          "FINALIZADO": null,
          "FINALIZADO_STRING": null,
          "SIGLATIPODOCUMENTO": null,
          "TEMPO_TRANSACAO": null,
          "USUARIO": "",
          "DAMAGEREPORT": null,
          "CPFMOTORISTA": null,
          "REMOTORISTA": null,
          "LANE": null,
          "ITVTRANSFERENCIA": null,
          "ITV": null,
          "TIPOENUM": 0,
          "LONGARINAENUM": null,
          "PLACADANIFICADA": false,
          "TFCVEICULOID": 0.0,
          "ISIMO": 0.0,
          "ISTRANSFERENCIA": 0,
          "NextAction": "",
          "PrevAction": "",
          "ActionReferenceId": 0.0,
          "_IOP": false,
          "UID": 0.0,
          "aCoMessageList": []
      },
      "OBSERVACAO": "",
      "PREVISTOS": "",
      "CONFIRMADOS": "",
      "NOVOS": "",
      "COLOCADOS": "",
      "CONFIRMALACRECOLOCADO": false,
      "INSPECAOFINALIZADA": false,
      "SEMLACRE": null,
      "PREENCHERLACREEMBRAPORT": false,
      "LACREEMBRAPORT": null,
      "OBSERVACOES": [],
      "NextAction": "",
      "PrevAction": "",
      "ActionReferenceId": 0.0,
      "UID": 0.0,
      "aCoMessageList": []
  },
  "ORDEM_INSPECAO": 1,
  "NextAction": null,
  "PrevAction": null,
  "ActionReferenceId": 0.0,
  "UID": 0.0,
  "aCoMessageList": []
};

 const mockContainerData = {
  "aCoEntity": null,
  "alsUpdate": [],
  "TFCCONTEINERINSPECAOID": 0.0,
  "TFCCONTEINERINSPECAORIID": null,
  "TFCCONTEINEROPERACAOID": 17228514.0,
  "TFCCONTEINERGMPREVISAOID": null,
  "EXTERNALID": 4524844836.0,
  "NROCONTEINER": "CSNU6575403",
  "CODIGOISO": "40DC",
  "CEALTURA": null,
  "CEDIREITA": null,
  "CEESQUERDA": null,
  "CEFRONTAL": null,
  "CESETTING": null,
  "CETRASEIRO": null,
  "CEVENTILACAO": null,
  "GENSET": "",
  "OCORRENCIA": "0001-01-01T00:00:00",
  "OCORRENCIA_STRING": "01/01/0001 00:00",
  "SAFEWEIGHT": 11561,
  "TARA": 3800,
  "TIPO": 0,
  "TIPO_DESCRIPTION": "Inspeção de Gate",
  "LONGARINA": null,
  "SEMLACRE": null,
  "TRA": null,
  "FREIGHTKIND": "FCL",
  "MODALIDADE": "IMPRT",
  "SIGLAMODALIDADE": "IMP",
  "SIGLAFREIGHTKIND": "CH",
  "FINALIZADO": null,
  "FINALIZADO_STRING": null,
  "SIGLATIPODOCUMENTO": null,
  "TEMPO_TRANSACAO": null,
  "USUARIO": "",
  "DAMAGEREPORT": null,
  "CPFMOTORISTA": null,
  "REMOTORISTA": null,
  "LANE": null,
  "ITVTRANSFERENCIA": null,
  "ITV": null,
  "TIPOENUM": 0,
  "LONGARINAENUM": null,
  "PLACADANIFICADA": false,
  "TFCVEICULOID": 0.0,
  "ISIMO": 0.0,
  "ISTRANSFERENCIA": 0,
  "NextAction": "",
  "PrevAction": "",
  "ActionReferenceId": 0.0,
  "_IOP": false,
  "UID": 0.0,
  "aCoMessageList": []
};


export const mockConteinerServicePesquisar = async () => {
  // Simula um atraso de rede
  await new Promise(resolve => setTimeout(resolve, 1000));
  return mockContainerData;
};

export const mockConteinerServiceEditar = async (container) => {
  // Simula um atraso de rede
  await new Promise(resolve => setTimeout(resolve, 1000));
  return container;
  
};

export const mockActionTfcConteinerInspecaoLacreResumoBuscar = async (container) => {
  // Simula um atraso de rede
  await new Promise(resolve => setTimeout(resolve, 1000));
  return mockTfcConteinerInspecaoLacreResumoBuscar;
  
};
